services:
  gateway-lsim:
    image: gateway-lsim
    container_name: gateway-lsim
    build:
      context: .
    ports:
      - "8762:8762"
    networks:
      - lsim-network
    depends_on:
      - server-lsim
    environment:
      - EUREKA_SERVER_URL=http://server-lsim:8761/eureka/

networks:
  lsim-network:
    external: true
