version: '3.8'

services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "8762:8762"
    environment:
      - SPRING_PROFILES_ACTIVE=development
    command: ["java", "-jar", "/app/gateway.jar"]

networks:
  app-network:
    external: true